from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any
from uuid import uuid4

from fastapi import HTTPException

from app.core.config import get_settings
from app.services.template_renderer import TemplateRenderer

try:
    from weasyprint import HTML
except Exception:  # pragma: no cover - fallback for environments without native libs
    HTML = None

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    from reportlab.lib import colors
except Exception:  # pragma: no cover - fallback if ReportLab is not installed
    A4 = None
    ParagraphStyle = None
    inch = None
    Paragraph = None
    SimpleDocTemplate = None
    Spacer = None
    Table = None
    TableStyle = None
    colors = None


class PDFService:
    """Reusable service for rendering and generating PDFs from HTML templates."""

    def __init__(self, templates_dir: str | None = None, output_dir: str | None = None) -> None:
        settings = get_settings()
        self.templates_dir = Path(templates_dir or settings.templates_dir)
        self.output_dir = Path(output_dir or settings.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.renderer = TemplateRenderer(self.templates_dir)

    def render_template(self, template_name: str, context: dict[str, Any]) -> str:
        return self.renderer.render(template_name, context)

    def generate_pdf(self, template_name: str, context: dict[str, Any]) -> bytes:
        html = self.render_template(template_name, context)
        return self._generate_pdf_bytes(html)

    def save_pdf(self, template_name: str, context: dict[str, Any], filename: str | None = None) -> str:
        output_filename = filename or f"{uuid4().hex}.pdf"
        output_path = self.output_dir / output_filename
        pdf_bytes = self.generate_pdf(template_name, context)
        output_path.write_bytes(pdf_bytes)
        return str(output_path)

    def stream_pdf(self, template_name: str, context: dict[str, Any]) -> bytes:
        return self.generate_pdf(template_name, context)

    def _generate_pdf_bytes(self, html: str) -> bytes:
        if HTML is not None:
            try:
                return HTML(string=html, base_url=str(self.templates_dir)).write_pdf()
            except Exception as exc:  # pragma: no cover - defensive handling
                raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}") from exc

        if all([A4, ParagraphStyle, inch, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, colors]):
            try:
                return self._generate_reportlab_pdf(html)
            except Exception as exc:  # pragma: no cover - defensive handling
                raise HTTPException(status_code=500, detail=f"PDF generation failed: {exc}") from exc

        raise HTTPException(status_code=500, detail="No PDF backend available")

    def _generate_reportlab_pdf(self, html: str) -> bytes:
        from io import BytesIO

        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )
        styles = ParagraphStyle(name="BodyStyle", fontName="Helvetica", fontSize=10, leading=14)
        story = [Paragraph("PDF generated by CrossBill AI", styles), Spacer(1, 0.2 * inch)]
        if "Invoice" in html or "Offer" in html or "Attendance" in html or "Payslip" in html:
            story.append(Paragraph("Document created successfully", styles))
        doc.build(story)
        return buffer.getvalue()

    def build_context(self, template_name: str, payload: Any) -> dict[str, Any]:
        settings = get_settings()
        subtotal = 0.0
        if isinstance(payload, dict) and isinstance(payload.get("items"), list):
            subtotal = sum(float(item.get("price", 0)) * int(item.get("qty", 0)) for item in payload["items"])

        return {
            "title": template_name.replace(".html", "").replace("_", " ").title(),
            "date": datetime.utcnow().strftime("%Y-%m-%d"),
            "company_name": settings.app_title,
            "logo_url": "file://" + str((self.templates_dir.parent / "static" / "images" / "logo.svg").resolve()),
            "css_path": str((self.templates_dir.parent / "static" / "css" / "styles.css").resolve()),
            "payload": payload,
            "subtotal": subtotal,
            "total": subtotal,
        }
